# Generated by Django 2.2.4 on 2020-01-29 13:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='match_number',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='round_in_match_number',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
