# Generated by Django 2.2.4 on 2020-01-30 10:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision',
            field=otree.db.models.StringField(choices=[('Action 1', 'Action 1'), ('Action 2', 'Action 2')], max_length=10000, null=True),
        ),
    ]
