# Generated by Django 2.2.4 on 2020-01-31 12:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_chat', '0003_player_chat_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chat_end_time',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
