# Generated by Django 2.2.4 on 2020-01-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_chat', '0008_auto_20200131_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='chat_end_time',
        ),
    ]
