# Generated by Django 2.2.4 on 2020-01-31 14:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_chat', '0009_remove_player_chat_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='chat_start_time',
        ),
        migrations.AddField(
            model_name='player',
            name='element_first_seen',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
