# Generated by Django 2.2.4 on 2020-01-31 14:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_chat', '0010_auto_20200131_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='element_first_seen',
        ),
        migrations.AddField(
            model_name='group',
            name='element_first_seen',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
